export const ACQUISITION_STAGES = [
  { id: 'new', label: 'New', color: 'text-info' },
  { id: 'contacted', label: 'Contacted', color: 'text-text-dim' },
  { id: 'qualified', label: 'Qualified', color: 'text-warning' },
  { id: 'follow_up', label: 'Follow-Up', color: 'text-gold' },
  { id: 'offer_made', label: 'Offer Made', color: 'text-gold-bright' },
  { id: 'underwriting', label: 'Underwriting', color: 'text-info' },
  { id: 'approved', label: 'Approved', color: 'text-success' },
  { id: 'under_contract', label: 'Under Contract', color: 'text-success' },
  { id: 'closing', label: 'Closing', color: 'text-success' },
  { id: 'closed', label: 'Closed', color: 'text-success' },
]

export const DISPOSITION_STAGES = [
  { id: 'locked_up', label: 'Locked Up', color: 'text-gold' },
  { id: 'marketing', label: 'Marketing', color: 'text-info' },
  { id: 'buyer_interested', label: 'Buyer Interested', color: 'text-warning' },
  { id: 'assigned', label: 'Assigned', color: 'text-gold-bright' },
  { id: 'dispo_closing', label: 'Closing', color: 'text-success' },
  { id: 'dispo_closed', label: 'Closed', color: 'text-success' },
]

export const MOCK_LEADS = [
  {
    id: '1',
    address: '1234 Oak Street, Phoenix, AZ 85001',
    status: 'new',
    pipeline: 'acquisitions',
    source: 'agent_finder',
    seller: { name: 'John Smith', phone: '(480) 555-0101', email: 'john@email.com' },
    agent: { name: 'Sarah Lee', phone: '(480) 555-1010', email: 'sarah@realty.com', brokerage: 'ABC Realty' },
    property: { type: 'Single Family', beds: 3, baths: 2, sqft: 1450, yearBuilt: 1998, condition: 'Good' },
    deal: { arv: 285000, repairs: 25000, offerAmount: null, wholesaleFee: 10000, askingPrice: 240000 },
    motivation: 'hot',
    nextAction: 'Call seller to discuss terms',
    nextActionDue: '2026-02-23',
    daysInStage: 2,
    createdAt: '2026-02-20',
    notes: [
      { text: 'Found via Agent Finder batch #47', date: '2026-02-20', author: 'Brandon' },
      { text: 'Agent mentioned seller is motivated, wants to close by March 15', date: '2026-02-21', author: 'Brad' },
    ],
    activities: [
      { type: 'created', text: 'Lead added from Agent Finder', date: '2026-02-20' },
      { type: 'note', text: 'Agent mentioned seller is motivated', date: '2026-02-21' },
    ],
    documents: [],
  },
  {
    id: '2',
    address: '567 Pine Avenue, Scottsdale, AZ 85251',
    status: 'qualified',
    pipeline: 'acquisitions',
    source: 'fsbo',
    seller: { name: 'Mike Williams', phone: '(602) 555-0303', email: 'mike@email.com' },
    agent: null,
    property: { type: 'Single Family', beds: 4, baths: 3, sqft: 2200, yearBuilt: 2005, condition: 'Fair' },
    deal: { arv: 425000, repairs: 45000, offerAmount: 280000, wholesaleFee: 15000, askingPrice: 350000 },
    motivation: 'warm',
    nextAction: 'Send LOI',
    nextActionDue: '2026-02-22',
    daysInStage: 5,
    createdAt: '2026-02-15',
    notes: [
      { text: 'FSBO listing on Zillow, owner wants to sell within 60 days', date: '2026-02-15', author: 'Brandon' },
    ],
    activities: [
      { type: 'created', text: 'Lead added from FSBO Finder', date: '2026-02-15' },
      { type: 'stage_change', text: 'Moved to Qualified', date: '2026-02-17' },
    ],
    documents: [],
  },
  {
    id: '3',
    address: '890 Maple Drive, Mesa, AZ 85201',
    status: 'underwriting',
    pipeline: 'acquisitions',
    source: 'manual',
    seller: { name: 'Lisa Chen', phone: '(480) 555-0404', email: 'lisa@email.com' },
    agent: { name: 'Tom Baker', phone: '(480) 555-4040', email: 'tom@homes.com', brokerage: 'Desert Realty' },
    property: { type: 'Single Family', beds: 3, baths: 2, sqft: 1600, yearBuilt: 1992, condition: 'Needs Work' },
    deal: { arv: 310000, repairs: 55000, offerAmount: 195000, wholesaleFee: 12000, askingPrice: 225000 },
    motivation: 'hot',
    nextAction: 'Waiting for underwriting results',
    nextActionDue: '2026-02-24',
    daysInStage: 3,
    createdAt: '2026-02-10',
    notes: [],
    activities: [
      { type: 'created', text: 'Manually added lead', date: '2026-02-10' },
      { type: 'stage_change', text: 'Moved to Underwriting', date: '2026-02-19' },
      { type: 'underwriting', text: 'Submitted for underwriting review', date: '2026-02-19' },
    ],
    documents: [{ name: 'mortgage_statement.pdf', date: '2026-02-19' }],
  },
  {
    id: '4',
    address: '321 Cedar Lane, Tempe, AZ 85281',
    status: 'offer_made',
    pipeline: 'acquisitions',
    source: 'agent_finder',
    seller: { name: 'Robert Brown', phone: '(480) 555-0505', email: 'robert@email.com' },
    agent: { name: 'Amy Wu', phone: '(480) 555-5050', email: 'amy@premier.com', brokerage: 'Premier Homes' },
    property: { type: 'Single Family', beds: 4, baths: 2, sqft: 1800, yearBuilt: 2001, condition: 'Good' },
    deal: { arv: 340000, repairs: 15000, offerAmount: 250000, wholesaleFee: 10000, askingPrice: 275000 },
    motivation: 'warm',
    nextAction: 'Follow up on LOI response',
    nextActionDue: '2026-02-21',
    daysInStage: 4,
    createdAt: '2026-02-08',
    notes: [{ text: 'LOI sent via LOI Generator', date: '2026-02-18', author: 'Brandon' }],
    activities: [
      { type: 'created', text: 'Lead added from Agent Finder', date: '2026-02-08' },
      { type: 'loi_sent', text: 'LOI #102 sent to Amy Wu', date: '2026-02-18' },
    ],
    documents: [{ name: 'LOI_321_Cedar.pdf', date: '2026-02-18' }],
  },
  {
    id: '5',
    address: '456 Elm Street, Gilbert, AZ 85233',
    status: 'under_contract',
    pipeline: 'acquisitions',
    source: 'agent_finder',
    seller: { name: 'David Park', phone: '(480) 555-0606', email: 'david@email.com' },
    agent: { name: 'Karen White', phone: '(480) 555-6060', email: 'karen@az.com', brokerage: 'AZ Homes' },
    property: { type: 'Single Family', beds: 5, baths: 3, sqft: 2600, yearBuilt: 2010, condition: 'Excellent' },
    deal: { arv: 510000, repairs: 5000, offerAmount: 380000, wholesaleFee: 20000, askingPrice: 420000 },
    motivation: 'cold',
    nextAction: 'Inspection scheduled Feb 25',
    nextActionDue: '2026-02-25',
    daysInStage: 1,
    createdAt: '2026-02-01',
    notes: [],
    activities: [
      { type: 'created', text: 'Lead added from Agent Finder', date: '2026-02-01' },
      { type: 'contract', text: 'Contract signed', date: '2026-02-21' },
    ],
    documents: [{ name: 'Purchase_Agreement.pdf', date: '2026-02-21' }],
  },
  {
    id: '6',
    address: '789 Birch Road, Chandler, AZ 85224',
    status: 'new',
    pipeline: 'acquisitions',
    source: 'fsbo',
    seller: { name: 'Maria Garcia', phone: '(602) 555-0707', email: 'maria@email.com' },
    agent: null,
    property: { type: 'Multi-Family', beds: 6, baths: 4, sqft: 3200, yearBuilt: 1985, condition: 'Fair' },
    deal: { arv: 450000, repairs: 80000, offerAmount: null, wholesaleFee: 15000, askingPrice: 320000 },
    motivation: 'hot',
    nextAction: 'Initial outreach call',
    nextActionDue: '2026-02-23',
    daysInStage: 1,
    createdAt: '2026-02-22',
    notes: [],
    activities: [{ type: 'created', text: 'Lead added from FSBO Finder', date: '2026-02-22' }],
    documents: [],
  },
  {
    id: '7',
    address: '222 Sunset Blvd, Phoenix, AZ 85004',
    status: 'contacted',
    pipeline: 'acquisitions',
    source: 'manual',
    seller: { name: 'James Taylor', phone: '(480) 555-0808', email: 'james@email.com' },
    agent: null,
    property: { type: 'Single Family', beds: 2, baths: 1, sqft: 1100, yearBuilt: 1975, condition: 'Needs Work' },
    deal: { arv: 195000, repairs: 40000, offerAmount: null, wholesaleFee: 8000, askingPrice: 145000 },
    motivation: 'warm',
    nextAction: 'Schedule property walkthrough',
    nextActionDue: '2026-02-24',
    daysInStage: 3,
    createdAt: '2026-02-19',
    notes: [{ text: 'Referred by a friend, seems interested', date: '2026-02-19', author: 'Brad' }],
    activities: [
      { type: 'created', text: 'Manually added', date: '2026-02-19' },
      { type: 'stage_change', text: 'Moved to Contacted', date: '2026-02-20' },
    ],
    documents: [],
  },
]
